<?php

namespace App\Filament\Resources;

use App\Filament\Resources\GameExclusiveResource\Pages;
use App\Models\GameExclusive;
use App\Models\Provider;
use BackedEnum;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\CreateAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms;
use Filament\Forms\Components\RichEditor;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Group;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Tables;
use Filament\Tables\Table;
use UnitEnum;

class GameExclusiveResource extends Resource
{
    protected static ?string $model = GameExclusive::class;

    protected static string|BackedEnum|null $navigationIcon = 'heroicon-o-puzzle-piece';

    protected static ?string $navigationLabel = 'Jogos Plataforma';

    protected static ?string $modelLabel = 'Jogos Plataforma';

    protected static string|UnitEnum|null $navigationGroup = 'Jogos';

    protected static ?string $slug = 'meus-jogos-exclusivos';

    protected static ?string $recordTitleAttribute = 'name';

    protected static ?int $navigationSort = -1;

    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count(); // TODO: Change the autogenerated stub
    }

    public static function getNavigationBadgeColor(): string|array|null
    {
        return static::getModel()::count() > 5 ? 'success' : 'warning'; // TODO: Change the autogenerated stub
    }

    public static function form(Schema $form): Schema
    {
        return $form
            ->schema([
                Section::make('Games')
                    ->description('Cadastrando um jogo')
                    ->schema([
                        Forms\Components\Select::make('provider_id')
                            ->label('Provedor')
                            ->placeholder('Selecione um provedor')
                            ->relationship(name: 'provider', titleAttribute: 'name')
                            ->options(
                                fn ($get) => Provider::query()
                                    ->pluck('name', 'id')
                            )
                            ->searchable()
                            ->preload()
                            ->live()
                            ->columnSpanFull(),

                        Group::make()
                            ->schema([
                                Forms\Components\TextInput::make('name')
                                    ->label('Nome do jogo')
                                    ->placeholder('Digite o nome do jogo')
                                    ->required()
                                    ->maxLength(191),
                                Forms\Components\TextInput::make('uuid')
                                    ->label('UUID')
                                    ->placeholder('Digite o UUID do jogo, a pasta onde o jogo está')
                                    ->required()
                                    ->maxLength(191),
                            ])->columns(2),

                        RichEditor::make('description')
                            ->columnSpanFull(),
                        Group::make()
                            ->schema([
                                Forms\Components\FileUpload::make('cover')
                                    ->label('Capa')
                                    ->placeholder('Carregue a capa do jogo')
                                    ->image()
                                    ->required(),
                                Forms\Components\FileUpload::make('icon')
                                    ->label('Icone')
                                    ->placeholder('Carregue a icone do jogo')
                                    ->image()
                                    ->required(),
                            ])->columns(2),
                        Group::make()
                            ->schema([
                                Forms\Components\TextInput::make('winLength')
                                    ->required()
                                    ->numeric()
                                    ->default(3),
                                Forms\Components\TextInput::make('loseLength')
                                    ->required()
                                    ->numeric()
                                    ->default(20),
                                Forms\Components\TextInput::make('influencer_winLength')
                                    ->required()
                                    ->numeric()
                                    ->default(20),
                                Forms\Components\TextInput::make('influencer_loseLength')
                                    ->required()
                                    ->numeric()
                                    ->default(1),
                            ])->columns(4),
                        Forms\Components\Toggle::make('active')
                            ->label('Ativar Jogo')
                            ->default(true)
                            ->required()
                            ->columnSpanFull(),
                    ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('provider.name')
                    ->label('Provedor')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('name')
                    ->label('Nome')
                    ->searchable(),

                Tables\Columns\ImageColumn::make('cover')
                    ->label('Capa'),
                Tables\Columns\ImageColumn::make('icon')
                    ->label('Icone'),

                Tables\Columns\TextColumn::make('winLength')
                    // ->toggleable(isToggledHiddenByDefault: true)
                    ->label('Vitoria')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('loseLength')
                    // ->toggleable(isToggledHiddenByDefault: true)
                    ->label('Perda')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('influencer_winLength')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('influencer_loseLength')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->numeric()
                    ->sortable(),
                Tables\Columns\ToggleColumn::make('active')
                    ->label('Ativo'),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Data')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                EditAction::make(),
            ])
            ->bulkActions(env('APP_DEMO') ? [] : [
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                CreateAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListGameExclusives::route('/'),
            'create' => Pages\CreateGameExclusive::route('/create'),
            'edit' => Pages\EditGameExclusive::route('/{record}/edit'),
        ];
    }
}
